#!/bin/bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_NAME=`realpath $0`
FGLJPDIR=`dirname $SCRIPT_NAME` 
#echo "FGLJPDIR=$FGLJPDIR"
export LC_ALL="en_US.UTF-8"
pushd "`pwd`" >/dev/null
cd "$FGLJPDIR"
#recompile only when needed
source "$FGLJPDIR/myfglcomp.sh"
myfglcomp mygetopt
myfglcomp URI
myfglcomp fgljp
popd > /dev/null
export FGLJPDIR
#exec fglrun -p $FGLJPDIR/fgljp.42m "$@"
exec fglrun "$FGLJPDIR/fgljp.42m" "$@"
